import numpy as np

arr = np.array([[1, -2, 3], [-4, 5, -6]])
absA = np.abs(arr)
flt = arr.flatten()
p25, p50, p75 = np.percentile(flt, [25, 50, 75])
c25 = np.percentile(arr, 25, axis=0)
c50 = np.percentile(arr, 50, axis=0)
c75 = np.percentile(arr, 75, axis=0)
r25 = np.percentile(arr, 25, axis=1)
r50 = np.percentile(arr, 50, axis=1)
r75 = np.percentile(arr, 75, axis=1)
mf = np.mean(flt)
mdf = np.median(flt)
sf = np.std(flt)
mc = np.mean(arr, axis=0)
mdc = np.median(arr, axis=0)
sc = np.std(arr, axis=0)
mr = np.mean(arr, axis=1)
mdr = np.median(arr, axis=1)
sr = np.std(arr, axis=1)
print("Q2 Abs:", absA)
print("Q2 Percentiles flat:", p25, p50, p75)
print("Q2 Percentiles col:", c25, c50, c75)
print("Q2 Percentiles row:", r25, r50, r75)
print("Q2 Mean/Med/Std flat:", mf, mdf, sf)
print("Q2 Mean/Med/Std col:", mc, mdc, sc)
print("Q2 Mean/Med/Std row:", mr, mdr, sr)